import express from "express";
import path from "path";
import fs from "fs";
import { exec } from "child_process";
import { createServer as createViteServer } from "vite";

async function startServer() {
  // On server start, ensure data directory and default seeds are configured without deleting existing data
  try {
    const dataDir = path.resolve(process.cwd(), "data");
    const activeP = path.join(dataDir, "active_candidates.json");
    const sampleP = path.join(dataDir, "sample_candidates.json");

    if (!fs.existsSync(activeP)) {
      fs.writeFileSync(activeP, "[]", "utf-8");
    }
    if (!fs.existsSync(sampleP)) {
      fs.writeFileSync(sampleP, "[]", "utf-8");
    }
    console.log("Startup directory structure verified.");
  } catch (cleanErr) {
    console.warn("Clean startup cleanup failed:", cleanErr);
  }

  const app = express();
  const PORT = 3000;

  // Middleware to parse JSON payloads large enough to handle multiple files
  app.use(express.json({ limit: "50mb" }));
  app.use(express.urlencoded({ limit: "50mb", extended: true }));

  // Helper helper to parse CSV with potential quotes and commas
  function parseCSV(csvContent: string): any[] {
    const lines = csvContent.split(/\r?\n/);
    if (lines.length === 0 || !lines[0]) return [];

    const headers = parseCSVLine(lines[0]);
    const records: any[] = [];

    for (let i = 1; i < lines.length; i++) {
      const line = lines[i];
      if (!line.trim()) continue;
      const values = parseCSVLine(line);
      const row: any = {};
      
      headers.forEach((h, idx) => {
        let val = values[idx] !== undefined ? values[idx] : "";
        // Strip outermost quotes
        if (val.startsWith('"') && val.endsWith('"')) {
          val = val.slice(1, -1);
        }
        row[h] = val;
      });
      records.push(row);
    }
    return records;
  }

  function parseCSVLine(line: string): string[] {
    const result: string[] = [];
    let current = "";
    let inQuotes = false;
    for (let i = 0; i < line.length; i++) {
      const char = line[i];
      if (char === '"') {
        inQuotes = !inQuotes;
      } else if (char === "," && !inQuotes) {
        result.push(current.trim());
        current = "";
      } else {
        current += char;
      }
    }
    result.push(current.trim());
    return result;
  }

  // 1. Get current candidates JSON content
  app.get("/api/candidates", (req, res) => {
    try {
      const p = path.resolve(process.cwd(), "data", "sample_candidates.json");
      if (fs.existsSync(p)) {
        const raw = fs.readFileSync(p, "utf-8");
        return res.json(JSON.parse(raw));
      }
      return res.status(404).json({ error: "Candidates seed file not found." });
    } catch (e: any) {
      return res.status(500).json({ error: e.message });
    }
  });

  // 2. Rank candidates (overwrites sample_candidates.json with uploaded content if provided, and runs python pipeline)
  app.post("/api/rank", (req, res) => {
    try {
      const { candidates } = req.body;
      
      // If candidates payload is specified, write it overwrite existing candidates catalog
      if (candidates) {
        const p = path.resolve(process.cwd(), "data", "sample_candidates.json");
        fs.writeFileSync(p, JSON.stringify(candidates, null, 2), "utf-8");

        const activeP = path.resolve(process.cwd(), "data", "active_candidates.json");
        fs.writeFileSync(activeP, JSON.stringify(candidates, null, 2), "utf-8");
      }

      // Execute Python main pipeline
      console.log("Running python main_pipeline.py...");
      exec("python3 main_pipeline.py", (err, stdout, stderr) => {
        if (err) {
          console.error("Pipeline run error:", stderr || err.message);
          return res.status(500).json({
            error: "Pipeline execution failed",
            details: stderr || err.message
          });
        }

        console.log("Pipeline stdout:", stdout);

        // Read compiled ranked leaderboard CSV
        const csvPath = path.resolve(process.cwd(), "data", "ranked_leaderboard.csv");
        if (fs.existsSync(csvPath)) {
          const csvContent = fs.readFileSync(csvPath, "utf-8");
          const parsedRecords = parseCSV(csvContent);
          return res.json({
            success: true,
            records: parsedRecords,
            stdout: stdout,
            rawCsv: csvContent
          });
        } else {
          return res.status(500).json({
            error: "Leaderboard file was not generated by pipeline",
            details: stdout
          });
        }
      });
    } catch (e: any) {
      console.error("Rank api error:", e);
      return res.status(500).json({ error: e.message });
    }
  });

  // 3. Serve Vite client or Static build
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Express Dev Server running at http://0.0.0.0:${PORT}`);
  });
}

startServer();
